version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  build-and-test:
    executor:
      name: node/default
    setup:
      steps:
        - run: $SUDO npm i mongodb -g
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: mongod
            - run: mocha test
workflows:
  build-and-test:
    jobs:
      - build-and-test
